apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-webapp     # <-- match this with K8S_DEPLOYMENT_NAME in Jenkinsfile
  labels:
    app: springboot-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-webapp
  template:
    metadata:
      labels:
        app: springboot-webapp
    spec:
      containers:
        - name: springboot-webapp
          # TODO: replace this with your real image name
          image: ajc64/springboot-webapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # Optional: env vars for MySQL if your app needs them
          env:
            - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql-service:3306/yourdb
            - name: SPRING_DATASOURCE_USERNAME
            value: youruser
            - name: SPRING_DATASOURCE_PASSWORD
            value: yourpass

