apiVersion: v1
kind: Service
metadata:
  name: springboot-webapp-service
spec:
  type: NodePort
  selector:
    app: springboot-webapp
  ports:
    - port: 8080        # service port inside cluster
      targetPort: 8080  # containerPort
      nodePort: 30090   # external NodePort (30000â€“32767 range)
